#!/bin/sh

npx concurrently \
  --kill-others-on-fail \
  --prefix "[{name}]" \
  --names "format,lint,typecheck" \
  --prefix-colors "bgMagenta.bold.white,bgGreen.bold.white,bgBlue.bold.white" \
    "npm run format --silent" \
    "npm run lint --silent" \
    "npm run typecheck --silent"
